apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/jegan-m/eks-node-app:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/jegan-m/eks-node-app:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: eks-node-app
        chartPath: charts/eks-node-app
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/jegan-m/eks-node-app'
          image.tag: '{{.DIGEST_HEX}}'
